/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DiscretePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  filters: [],
  hideMatches: true,
  combineWithAnd: false,
  enableExplorerFilter: true
};

// src/settings.ts
var import_obsidian = require("obsidian");
var DiscreteSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Enable file explorer filtering").setDesc("Apply the metadata filters to the file explorer to hide or show files based on their frontmatter.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableExplorerFilter).onChange(async (value) => {
      this.plugin.settings.enableExplorerFilter = value;
      await this.plugin.saveSettings();
      if (!value) {
        const style = document.getElementById("metadata-filter-styles");
        if (style)
          style.remove();
      } else {
        await this.plugin.applyFiltersToExplorer();
      }
      this.plugin.updateRibbonIcon();
      this.app.workspace.trigger("file-explorer:refresh");
    }));
    new import_obsidian.Setting(containerEl).setName("Filter behavior").setHeading();
    new import_obsidian.Setting(containerEl).setName("Hide matching files").setDesc("When enabled, matching files will be hidden instead of shown").addToggle((toggle) => toggle.setValue(this.plugin.settings.hideMatches).onChange(async (value) => {
      this.plugin.settings.hideMatches = value;
      await this.plugin.saveSettings();
      if (this.plugin.settings.enableExplorerFilter) {
        const oldStyle = document.getElementById("metadata-filter-styles");
        if (oldStyle)
          oldStyle.remove();
        await this.plugin.applyFiltersToExplorer();
      }
      this.app.workspace.trigger("file-explorer:refresh");
    }));
    new import_obsidian.Setting(containerEl).setName("Combine filters with AND").setDesc("When enabled, files must match ALL filters. When disabled, files must match ANY filter").addToggle((toggle) => toggle.setValue(this.plugin.settings.combineWithAnd).onChange(async (value) => {
      this.plugin.settings.combineWithAnd = value;
      await this.plugin.saveSettings();
      if (this.plugin.settings.enableExplorerFilter) {
        await this.plugin.applyFiltersToExplorer();
      }
      this.app.workspace.trigger("file-explorer:refresh");
    }));
    new import_obsidian.Setting(containerEl).setName("Rules").setHeading();
    const table = containerEl.createEl("table", { cls: "filters-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    const headers = [
      { title: "Key", desc: "Frontmatter field to filter on" },
      { title: "Operator", desc: "How to compare values" },
      { title: "Type", desc: "Type of value to match" },
      { title: "Value", desc: "Value to compare against" },
      { title: "", desc: "" }
    ];
    headers.forEach((header) => {
      const th = headerRow.createEl("th");
      th.createEl("div", { text: header.title });
      if (header.desc) {
        th.createEl("div", {
          text: header.desc,
          cls: "header-description"
        });
      }
    });
    const tbody = table.createEl("tbody");
    this.plugin.settings.filters.forEach((filter, index) => {
      const row = tbody.createEl("tr");
      const keyCell = row.createEl("td");
      const keyInput = keyCell.createEl("input", {
        type: "text",
        placeholder: "Enter key (e.g., tags, status)",
        value: filter.key
      });
      keyInput.addEventListener("change", async () => {
        filter.key = keyInput.value;
        await this.plugin.saveSettings();
        if (this.plugin.settings.enableExplorerFilter) {
          await this.plugin.applyFiltersToExplorer();
        }
      });
      const operatorCell = row.createEl("td", { cls: "operator-cell" });
      const operators = [
        { value: "equals", label: "=", tooltip: "Equals exactly" },
        { value: "contains", label: "\u2208", tooltip: "Contains (text only)" },
        { value: "exists", label: "\u2203", tooltip: "Field exists" },
        { value: "includes", label: "\u2282", tooltip: "List includes value" },
        { value: "greater", label: ">", tooltip: "Greater than" },
        { value: "less", label: "<", tooltip: "Less than" }
      ];
      operators.forEach((op) => {
        const btn = operatorCell.createEl("button", {
          text: op.label,
          cls: `operator-button ${filter.operator === op.value ? "is-active" : ""}`,
          attr: { title: op.tooltip }
        });
        btn.addEventListener("click", async () => {
          operatorCell.findAll(".operator-button").forEach((b) => b.removeClass("is-active"));
          btn.addClass("is-active");
          filter.operator = op.value;
          await this.plugin.saveSettings();
          if (this.plugin.settings.enableExplorerFilter) {
            await this.plugin.applyFiltersToExplorer();
          }
          this.display();
        });
      });
      const typeCell = row.createEl("td");
      if (!["exists", "greater", "less", "contains"].includes(filter.operator)) {
        const typeSelect = typeCell.createEl("select");
        const types = {
          "string": "Text",
          "number": "Number",
          "array": "List/array",
          "boolean": "Yes/No"
        };
        Object.entries(types).forEach(([value, label]) => {
          const option = typeSelect.createEl("option", {
            value,
            text: label
          });
          if (value === filter.type) {
            option.selected = true;
          }
        });
        typeSelect.addEventListener("change", async () => {
          filter.type = typeSelect.value;
          await this.plugin.saveSettings();
          if (this.plugin.settings.enableExplorerFilter) {
            await this.plugin.applyFiltersToExplorer();
          }
          this.display();
        });
      } else {
        if (["greater", "less"].includes(filter.operator)) {
          filter.type = "number";
        } else if (filter.operator === "contains") {
          filter.type = "string";
        }
        typeCell.addClass("discrete-empty-cell");
      }
      const valueCell = row.createEl("td");
      if (filter.operator !== "exists") {
        if (filter.type === "boolean") {
          const select = valueCell.createEl("select");
          ["true", "false"].forEach((value) => {
            const option = select.createEl("option", {
              value,
              text: value === "true" ? "Yes" : "No"
            });
            if (value === filter.value) {
              option.selected = true;
            }
          });
          select.addEventListener("change", async () => {
            filter.value = select.value;
            await this.plugin.saveSettings();
            if (this.plugin.settings.enableExplorerFilter) {
              await this.plugin.applyFiltersToExplorer();
            }
          });
        } else {
          const input = valueCell.createEl("input", {
            type: filter.type === "number" ? "number" : "text",
            placeholder: filter.type === "number" ? "Enter a number" : filter.type === "array" ? "Enter value to search for in list" : "Enter text value",
            value: filter.value
          });
          input.addEventListener("change", async () => {
            filter.value = input.value;
            await this.plugin.saveSettings();
            if (this.plugin.settings.enableExplorerFilter) {
              await this.plugin.applyFiltersToExplorer();
            }
          });
        }
      }
      const removeCell = row.createEl("td");
      const removeButton = removeCell.createEl("button", {
        text: "\xD7",
        cls: "discrete-remove-filter"
      });
      removeButton.addEventListener("click", async () => {
        this.plugin.settings.filters.splice(index, 1);
        await this.plugin.saveSettings();
        await this.plugin.applyFiltersToExplorer();
        this.display();
      });
    });
    const emptyRow = tbody.createEl("tr");
    emptyRow.createEl("td");
    emptyRow.createEl("td");
    emptyRow.createEl("td");
    emptyRow.createEl("td");
    const addCell = emptyRow.createEl("td");
    const addButton = addCell.createEl("button", {
      text: "+",
      cls: "discrete-remove-filter"
    });
    addButton.addEventListener("click", async () => {
      this.plugin.settings.filters.push({
        key: "",
        value: "",
        operator: "equals",
        type: "string"
      });
      await this.plugin.saveSettings();
      if (this.plugin.settings.enableExplorerFilter) {
        await this.plugin.applyFiltersToExplorer();
      }
      this.display();
    });
    const versionEl = containerEl.createDiv("metadata-filter-version");
    versionEl.setText(`v${this.plugin.manifest.version}`);
  }
};

// src/main.ts
var DiscretePlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.ribbonIconEl = this.addRibbonIcon("eye", "Toggle file explorer filtering", (evt) => {
      this.toggleFiltering();
    });
    this.updateRibbonIcon();
    this.addSettingTab(new DiscreteSettingTab(this.app, this));
    this.registerEvent(this.app.workspace.on("file-menu", (menu, file) => {
      menu.addItem((item) => {
        item.setTitle("Filter by metadata").setIcon("filter").onClick(async () => {
          var _a;
          if (file instanceof import_obsidian2.TFile) {
            const metadata = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
            if (metadata) {
              await this.filterByMetadata(metadata);
            }
          }
        });
      });
    }));
    this.registerEvent(this.app.workspace.on("file-explorer:create", () => {
      if (this.settings.enableExplorerFilter && this.settings.filters.length > 0) {
        this.applyFiltersToExplorer();
      }
    }));
    this.registerEvent(this.app.workspace.on("layout-change", () => {
      const fileExplorer = this.app.workspace.getLeavesOfType("file-explorer")[0];
      if (fileExplorer && this.settings.enableExplorerFilter && this.settings.filters.length > 0) {
        this.applyFiltersToExplorer();
      }
    }));
    this.registerEvent(this.app.vault.on("modify", () => {
      if (this.settings.enableExplorerFilter && this.settings.filters.length > 0) {
        this.applyFiltersToExplorer();
      }
    }));
    this.app.workspace.onLayoutReady(() => {
      if (this.settings.enableExplorerFilter && this.settings.filters.length > 0) {
        this.applyFiltersToExplorer();
      }
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  updateRibbonIcon() {
    if (this.ribbonIconEl) {
      const tooltip = this.settings.enableExplorerFilter ? "Disable file explorer filtering" : "Enable file explorer filtering";
      this.ribbonIconEl.empty();
      if (this.settings.enableExplorerFilter) {
        this.ribbonIconEl.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-eye-closed-icon lucide-eye-closed"><path d="m15 18-.722-3.25"/><path d="M2 8a10.645 10.645 0 0 0 20 0"/><path d="m20 15-1.726-2.05"/><path d="m4 15 1.726-2.05"/><path d="m9 18 .722-3.25"/></svg>`;
      } else {
        (0, import_obsidian2.setIcon)(this.ribbonIconEl, "eye");
      }
      this.ribbonIconEl.setAttribute("aria-label", tooltip);
      this.ribbonIconEl.setAttribute("data-tooltip", tooltip);
    }
  }
  async toggleFiltering() {
    this.settings.enableExplorerFilter = !this.settings.enableExplorerFilter;
    await this.saveSettings();
    if (!this.settings.enableExplorerFilter) {
      const style = document.getElementById("metadata-filter-styles");
      if (style)
        style.remove();
    } else {
      if (this.settings.filters.length > 0) {
        await this.applyFiltersToExplorer();
      }
    }
    this.updateRibbonIcon();
    this.app.workspace.trigger("file-explorer:refresh");
  }
  async filterByMetadata(metadata) {
    const key = Object.keys(metadata)[0];
    const value = metadata[key];
    const filter = {
      key,
      value: value.toString(),
      operator: Array.isArray(value) ? "includes" : typeof value === "number" ? "equals" : typeof value === "boolean" ? "equals" : "contains",
      type: Array.isArray(value) ? "array" : typeof value === "number" ? "number" : typeof value === "boolean" ? "boolean" : "string"
    };
    this.settings.filters.push(filter);
    await this.saveSettings();
    this.app.workspace.trigger("file-explorer:refresh");
  }
  evaluateFilter(metadata, filter) {
    const value = metadata[filter.key];
    if (filter.operator === "exists") {
      return value !== void 0 && value !== null;
    }
    if (value === void 0 || value === null) {
      return false;
    }
    switch (filter.operator) {
      case "equals":
        if (filter.type === "number") {
          return Number(value) === Number(filter.value);
        }
        if (filter.type === "boolean") {
          return String(value).toLowerCase() === filter.value.toLowerCase();
        }
        return String(value).toLowerCase() === filter.value.toLowerCase();
      case "contains":
        return String(value).toLowerCase().includes(filter.value.toLowerCase());
      case "includes":
        if (Array.isArray(value)) {
          return value.some((v) => String(v).toLowerCase() === filter.value.toLowerCase());
        }
        return false;
      case "greater":
        return Number(value) > Number(filter.value);
      case "less":
        return Number(value) < Number(filter.value);
      default:
        return false;
    }
  }
  async applyFiltersToExplorer() {
    var _a;
    const fileExplorer = this.app.workspace.getLeavesOfType("file-explorer")[0];
    if (!fileExplorer)
      return;
    const files = this.app.vault.getMarkdownFiles();
    const visibleFiles = /* @__PURE__ */ new Set();
    for (const file of files) {
      const metadata = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
      if (!metadata) {
        if (this.settings.hideMatches) {
          visibleFiles.add(file.path);
        }
        continue;
      }
      const matchesAll = this.settings.filters.every((f) => this.evaluateFilter(metadata, f));
      const matchesAny = this.settings.filters.some((f) => this.evaluateFilter(metadata, f));
      const matches = this.settings.combineWithAnd ? matchesAll : matchesAny;
      const shouldBeVisible = this.settings.hideMatches ? !matches : matches;
      if (shouldBeVisible) {
        visibleFiles.add(file.path);
      }
    }
    const style = document.createElement("style");
    style.id = "metadata-filter-styles";
    const oldStyle = document.getElementById("metadata-filter-styles");
    if (oldStyle)
      oldStyle.remove();
    const hideRules = files.filter((f) => !visibleFiles.has(f.path)).map((f) => `.nav-file-title[data-path="${CSS.escape(f.path)}"] { display: none !important; }`).join("\n");
    style.textContent = hideRules;
    document.head.appendChild(style);
  }
  onunload() {
    const style = document.getElementById("metadata-filter-styles");
    if (style)
      style.remove();
  }
};

/* nosourcemap */